baseURL = "/"
title = "PGP SMS"
defaultContentLanguage = "pl"
defaultContentLanguageInSubdir = false
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]

[languages]
  [languages.pl]
    languageCode = "pl-PL"
    languageName = "Polski"
    weight = 1
    [languages.pl.params]
      description = "Klienckie narzędzie OpenPGP do wiadomości SMS."

  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    [languages.en.params]
      description = "Client-side OpenPGP utility for SMS."
